Repository geertmeersman/robonect, pull requests merged in 2023-08, with the labels that each got.

#74 doc: Document REST API username/password
  README.md
Labels: documentation

#75 fix: timer ID correction in services, fixes #68
  custom_components/robonect/const.py
  images/screenshots/config_flow_2.png
Labels: patch, fix

#76 feat: switch entity for timers. Replaces timer sensors, fixes #69
  VERSION
  custom_components/robonect/__init__.py
  custom_components/robonect/binary_sensor.py
  custom_components/robonect/button.py
  custom_components/robonect/config_flow.py
  custom_components/robonect/const.py
  custom_components/robonect/definitions.py
  custom_components/robonect/manifest.json
  custom_components/robonect/models.py
  custom_components/robonect/switch.py
  custom_components/robonect/translations/de.json
  custom_components/robonect/translations/en.json
  custom_components/robonect/translations/fr.json
  custom_components/robonect/translations/nl.json
  custom_components/robonect/utils.py
Labels: minor, feat

#77 fix: hex2weekdays, D400 First line should end with a period
  custom_components/robonect/utils.py
Labels: patch, fix

#78 docs: finally merged into HACS default
  README.md
Labels: patch, docs

#80 fix: names added for service fields
  custom_components/robonect/services.yaml
Labels: patch, fix
